version: '3'
services:
  backend:
    image: python:3.10.12
    working_dir: /srv/backend
    volumes:
      - ./src:/srv/backend
    entrypoint: sh -c "ls; cd /srv/backend && pip install -r requirements.txt && python app.py"
    environment:
      - MONGO_CONN_STR=mongodb://user:pass@mongodb:27017
    ports:
      - "5000:5000"
    networks:
      - mongo-net

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge
